"""Collection classes for managing multiple tools."""
from typing import Any, Dict, List

from app.exceptions import ToolError
from app.tool.base import BaseTool, ToolFailure, ToolResult


class ToolCollection:
    """
    A collection class for managing and executing multiple tools.
    
    The ToolCollection serves as a container and manager for a set of tools in the
    OpenManus framework. It provides a unified interface for tool registration,
    lookup, parameter generation, and execution. This centralized management
    simplifies tool handling throughout the application and enables operations
    across multiple tools.
    
    The collection maintains both a tuple of tools for ordered iteration and a
    name-to-tool mapping for efficient lookups. This dual representation allows
    for both sequential processing and direct access patterns.
    
    This class is a core component in the OpenManus tool system, serving as the
    primary interface between agents and the available tools.
    """

    def __init__(self, *tools: BaseTool):
        """
        Initialize a tool collection with the provided tools.
        
        This constructor accepts any number of BaseTool instances and registers
        them in the collection. It builds both a tuple for ordered access and
        a dictionary mapping tool names to their instances for direct lookup.
        
        Args:
            *tools: Variable number of BaseTool instances to include in the collection.
                   These tools will be immediately available for execution.
        """
        self.tools = tools  # Tuple of tools for ordered iteration
        self.tool_map = {tool.name: tool for tool in tools}  # Dictionary for O(1) lookups by name

    def __iter__(self):
        """
        Make the collection iterable, yielding tools in their original order.
        
        This method enables using the collection directly in for loops and other
        iteration contexts, providing access to the tools in the order they were
        added.
        
        Returns:
            An iterator over the tools in the collection.
        """
        return iter(self.tools)

    def to_params(self) -> List[Dict[str, Any]]:
        """
        Convert all tools in the collection to their parameter representations.
        
        This method generates a list of parameter dictionaries for all tools in the
        collection, suitable for passing to LLMs or other systems that need to know
        about available tools and their parameters.
        
        Returns:
            A list of dictionaries, each containing the parameter representation
            of a tool as generated by its to_param() method.
        """
        return [tool.to_param() for tool in self.tools]

    async def execute(
        self, *, name: str, tool_input: Dict[str, Any] = None
    ) -> ToolResult:
        """
        Execute a specific tool by name with the provided inputs.
        
        This method looks up a tool by name and executes it with the given inputs.
        It handles error cases such as invalid tool names and execution failures,
        wrapping them in appropriate ToolResult objects.
        
        Args:
            name: The name of the tool to execute.
            tool_input: A dictionary of input parameters to pass to the tool.
                       Defaults to None (empty dict).
        
        Returns:
            A ToolResult object containing the result of the execution or an error.
            If the tool name is invalid or execution fails, a ToolFailure is returned.
        """
        # Look up the tool by name
        tool = self.tool_map.get(name)
        if not tool:
            # Return a failure result if the tool doesn't exist
            return ToolFailure(error=f"Tool {name} is invalid")
        try:
            # Execute the tool with the provided inputs
            result = await tool(**(tool_input or {}))
            return result
        except ToolError as e:
            # Catch and wrap any tool-specific errors
            return ToolFailure(error=e.message)

    async def execute_all(self) -> List[ToolResult]:
        """
        Execute all tools in the collection sequentially.
        
        This method runs each tool in the collection in the order they were added,
        with no parameters. It collects the results of all executions, including
        any failures, and returns them as a list.
        
        This is useful for initialization tasks, health checks, or any scenario
        where all tools need to be run regardless of their individual outcomes.
        
        Returns:
            A list of ToolResult objects, one for each tool in the collection,
            in the same order as the tools.
        """
        results = []
        for tool in self.tools:
            try:
                # Execute each tool with no parameters
                result = await tool()
                results.append(result)
            except ToolError as e:
                # Catch and wrap any tool-specific errors
                results.append(ToolFailure(error=e.message))
        return results

    def get_tool(self, name: str) -> BaseTool:
        """
        Retrieve a tool from the collection by name.
        
        This method provides direct access to a tool instance by its name,
        allowing for inspection or manipulation of the tool outside the
        normal execution flow.
        
        Args:
            name: The name of the tool to retrieve.
        
        Returns:
            The BaseTool instance with the given name, or None if no such tool exists.
        """
        return self.tool_map.get(name)

    def add_tool(self, tool: BaseTool):
        """
        Add a single tool to the collection.
        
        This method registers a new tool in the collection, making it available
        for execution. It updates both the ordered tuple and the lookup dictionary.
        
        Args:
            tool: The BaseTool instance to add to the collection.
        
        Returns:
            The ToolCollection instance, allowing for method chaining.
        """
        # Add to the tuple of tools (maintaining order)
        self.tools += (tool,)
        # Add to the lookup dictionary
        self.tool_map[tool.name] = tool
        # Return self for method chaining
        return self

    def add_tools(self, *tools: BaseTool):
        """
        Add multiple tools to the collection at once.
        
        This method registers multiple new tools in the collection, making them
        available for execution. It's a convenience wrapper around add_tool.
        
        Args:
            *tools: Variable number of BaseTool instances to add to the collection.
        
        Returns:
            The ToolCollection instance, allowing for method chaining.
        """
        for tool in tools:
            self.add_tool(tool)
        # Return self for method chaining
        return self
